// Cable Attachment Registry — source authority model.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0.

#ifndef CABLE_REGISTRY_AUTHORITY_HPP
#define CABLE_REGISTRY_AUTHORITY_HPP

#include <cstdint>
#include <string>

#include "cable_registry/ids.hpp"

namespace cable_registry {

/// How much weight a claim from a source carries when two sources disagree.
///
/// The class is the primary key and the numeric rank only breaks ties inside
/// one class, so a high ranked speculation can never outrank a low ranked
/// operator declaration. This ordering is the whole answer to "which source is
/// authoritative enough": nothing else, and in particular no timestamp,
/// participates.
enum class AuthorityClass : std::uint8_t {
  /// Generated or replayed data with no physical observation behind it.
  Speculative = 0,
  /// Bulk import from an asset system that may lag reality.
  Imported = 1,
  /// Automated observation of a physical fact.
  Observed = 2,
  /// A human or a runbook declares the intended physical state.
  Declared = 3,
  /// The system of record for the physical plant.
  Authoritative = 4,
};

CABLE_REGISTRY_API const char* to_string(AuthorityClass value) noexcept;
CABLE_REGISTRY_API bool parse_authority_class(std::string_view text, AuthorityClass& out) noexcept;

/// A totally ordered authority value.
struct Authority {
  AuthorityClass authority_class = AuthorityClass::Speculative;
  std::uint32_t rank = 0;

  friend constexpr bool operator==(const Authority&, const Authority&) noexcept = default;
  friend constexpr auto operator<=>(const Authority&, const Authority&) noexcept = default;
};

/// How a source learned the fact it publishes.
enum class ProvenanceClass : std::uint8_t {
  Unknown = 0,
  /// Typed into a runbook by a human.
  OperatorEntry,
  /// Imported from a DCIM or asset management system.
  AssetImport,
  /// Produced by an automated discovery agent that observed the physical fact.
  DiscoveryAgent,
  /// Derived from a physical measurement such as optical reflectometry.
  PhysicalMeasurement,
  /// Produced by a scripted reconciliation job.
  Reconciliation,
  /// Generated by a test harness. Never mixed into production data.
  Synthetic,
};

CABLE_REGISTRY_API const char* to_string(ProvenanceClass value) noexcept;
CABLE_REGISTRY_API bool parse_provenance_class(std::string_view text, ProvenanceClass& out) noexcept;

/// A registered evidence source.
struct SourceDescriptor {
  SourceId id{};
  /// Operator facing name, unique per source id but not an identity.
  std::string name;
  Authority authority{};
  /// Administrative domain the source speaks for, for example a site or a
  /// fabric name. Informational: it never influences conflict resolution.
  std::string administrative_domain;

  friend bool operator==(const SourceDescriptor&, const SourceDescriptor&) noexcept = default;
};

} // namespace cable_registry

#endif // CABLE_REGISTRY_AUTHORITY_HPP
